# Generated by Django 4.1.6 on 2023-02-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('phone_ID', models.CharField(blank=True, max_length=40)),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(blank=True, default='Free', max_length=20)),
                ('subscription_status', models.CharField(blank=True, default='Active', max_length=20)),
                ('free_prompt_count', models.IntegerField(default=0)),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.userprofile')),
            ],
        ),
    ]
